version: '2'

services:
  node:
    container_name: app
    build:
      context: .
      args:
        - NODE_ENV=development
    command: ["node", "./server.js"]
    ports:
      - "8080:8080"
      - "5858:5858"
      - "9229:9229"
    volumes:
      - .:/opt/app
      - notused:/opt/app/node_modules
    environment:
      NODE_ENV: development
      PORT: 8080

volumes:
    notused:
